name: Build Cork

on:
  push:
    branches: [ v0.9.0 ]
  workflow_dispatch: # Permette di eseguire manualmente

jobs:
  build-windows:
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v4
      with:
        ref: v0.9.0
    
    - name: Setup MSVC
      uses: microsoft/setup-msbuild@v1
    
    - name: Install dependencies
      run: |
        # Installa le dipendenze necessarie
        choco install cmake --installargs 'ADD_CMAKE_TO_PATH=System'
        
    - name: Configure CMake
      run: |
        mkdir build
        cd build
        cmake .. -G "Visual Studio 17 2022" -A x64
        
    - name: Build
      run: |
        cd build
        cmake --build . --config Release
        
    - name: Upload Cork.exe
      uses: actions/upload-artifact@v4
      with:
        name: Cork-Windows-x64
        path: build/Release/*.exe

  build-linux:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
      with:
        ref: v0.9.0
        
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y cmake build-essential libgmp-dev
        
    - name: Configure and Build
      run: |
        mkdir build && cd build
        cmake ..
        make -j$(nproc)
        
    - name: Upload Cork executable
      uses: actions/upload-artifact@v4
      with:
        name: Cork-Linux-x64
        path: build/cork
