name: Build Cork Windows

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v4
      with:
        ref: master
        
    - name: Setup Visual Studio
      uses: microsoft/setup-msbuild@v2
      
    - name: Install CMake
      run: choco install cmake --installargs 'ADD_CMAKE_TO_PATH=System'
      
    - name: Install MPIR with vcpkg
      run: |
        git clone https://github.com/Microsoft/vcpkg.git
        cd vcpkg
        .\bootstrap-vcpkg.bat
        .\vcpkg install mpir:x64-windows
        
    - name: Configure CMake with vcpkg
      run: |
        mkdir build
        cd build
        cmake .. -G "Visual Studio 17 2022" -A x64 -DCMAKE_TOOLCHAIN_FILE="vcpkg/scripts/buildsystems/vcpkg.cmake"
        
    - name: Build Cork
      run: |
        cd build
        cmake --build . --config Release --verbose
        
    - name: List build output
      run: |
        Get-ChildItem -Recurse build/
        
    - name: Upload Cork.exe
      uses: actions/upload-artifact@v4
      with:
        name: Cork-Windows-x64
        path: |
          build/**/*.exe
          build/**/*.dll
