name: Build Cork Windows

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v4
      with:
        ref: master
        
    - name: Setup Visual Studio
      uses: microsoft/setup-msbuild@v2
      
    - name: Install CMake
      run: choco install cmake --installargs 'ADD_CMAKE_TO_PATH=System'
      
    - name: Install MPIR
      run: |
        Invoke-WebRequest -Uri "https://github.com/wbhart/mpir/releases/download/mpir-3.0.0/mpir-3.0.0-x64-windows-binaries.zip" -OutFile "mpir.zip"
        Expand-Archive -Path "mpir.zip" -DestinationPath "C:\mpir"
        
    - name: Configure CMake with MPIR
      run: |
        mkdir build
        cd build
        cmake .. -G "Visual Studio 17 2022" -A x64 -DMPIR_ROOT="C:\mpir" -DCMAKE_PREFIX_PATH="C:\mpir"
        
    - name: Build Cork
      run: |
        cd build
        cmake --build . --config Release --verbose
        
    - name: List build output
      run: |
        Get-ChildItem -Recurse build/
        
    - name: Upload Cork.exe
      uses: actions/upload-artifact@v4
      with:
        name: Cork-Windows-x64
        path: |
          build/**/*.exe
          build/**/*.dll
