name: Build Cork Windows
on: workflow_dispatch

jobs:
  build:
    runs-on: windows-2022
    steps:
      - uses: actions/checkout@v4

      - uses: ilammy/msvc-dev-cmd@v1

      - name: Set up vcpkg + deps
        run: |
          git clone https://github.com/microsoft/vcpkg.git C:/vcpkg
          C:/vcpkg/bootstrap-vcpkg.bat
          C:/vcpkg/vcpkg integrate install
          C:/vcpkg/vcpkg install boost:x64-windows mpir:x64-windows tbb:x64-windows eigen3:x64-windows

      - name: Configure (Clang CL, no tests, no /WX)
        run: |
          cmake -S . -B build `
            -G "Visual Studio 17 2022" -T ClangCL -A x64 `
            -DCMAKE_TOOLCHAIN_FILE=C:/vcpkg/scripts/buildsystems/vcpkg.cmake `
            -DCORK_USE_SYSTEM_EIGEN=ON `
            -DCORK_WITH_TESTING=OFF -DBUILD_TESTING=OFF `
            -DCORK_BUILD_UNITTEST=OFF -DCORK_BUILD_REGRESSION=OFF `
            -DCMAKE_CXX_FLAGS="/WX-"                 #  🔹 disattiva «warnings as errors»

      - name: Build (Release)
        run: cmake --build build --config Release --parallel

      - name: Upload Cork.exe
        uses: actions/upload-artifact@v4
        with:
          name: cork-exe
          path: build/Release/Cork.exe
