# .github/workflows/windows.yml

name: Build Cork Windows

on: workflow_dispatch

jobs:
  build-windows:
    runs-on: windows-2022

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Set up MSVC + Clang-CL
        uses: ilammy/msvc-dev-cmd@v1

      - name: Install vcpkg dependencies
        run: |
          if (Test-Path C:/vcpkg) { Remove-Item -Recurse -Force C:/vcpkg }
          git clone https://github.com/microsoft/vcpkg.git C:/vcpkg
          C:/vcpkg/bootstrap-vcpkg.bat -disableMetrics
          C:/vcpkg/vcpkg integrate install
          C:/vcpkg/vcpkg install boost:x64-windows mpir:x64-windows tbb:x64-windows eigen3:x64-windows

      - name: Configure (Clang-CL, enable exceptions)
        run: cmake -S . -B build -G "Visual Studio 17 2022" -T ClangCL -A x64 -DCMAKE_TOOLCHAIN_FILE="C:/vcpkg/scripts/buildsystems/vcpkg.cmake" -DCMAKE_CXX_FLAGS="/EHsc /bigobj /W3 /Zi" -DCMAKE_C_FLAGS="/bigobj /W3 /Zi" -DCORK_USE_SYSTEM_EIGEN=ON -DCORK_WITH_TESTING=OFF -DBUILD_TESTING=OFF -DCORK_BUILD_UNITTEST=OFF -DCORK_BUILD_REGRESSION=OFF

      - name: Build (Release)
        run: cmake --build build --config Release --parallel

      - name: Upload Cork executable
        uses: actions/upload-artifact@v4
        with:
          name: cork-exe
          path: build/Release/**
