name: Build Cork Windows

on: workflow_dispatch   # lo lancerai a mano

jobs:
  build:
    runs-on: windows-2022
    steps:
      - uses: actions/checkout@v4

      - name: Set up MSVC + Ninja
        uses: ilammy/msvc-dev-cmd@v1

      - name: Install vcpkg dependencies
        uses: lukka/run-vcpkg@v11
        with:
          setupOnly: true          # usa il manifest del repo

      - name: Configure (ClangCL)
        run: |
          cmake -S . -B build ^
                -G "Visual Studio 17 2022" -T ClangCL -A x64 ^
                -DCORK_USE_SYSTEM_EIGEN=ON -DBUILD_TESTING=OFF

      - name: Build
        run: cmake --build build --config Release --parallel

      - name: Upload Cork.exe
        uses: actions/upload-artifact@v4
        with:
          name: cork-exe
          path: build/Release/Cork.exe
